# Generated by Django 4.2.5 on 2023-09-21 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=300, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=300, verbose_name='действие')),
                ('is_nice_habit', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.IntegerField(choices=[(1, 'раз в день'), (2, 'раз в 2 дня'), (3, 'раз в 3 дня'), (4, 'раз в 4 дня'), (5, 'раз в 5 дней'), (6, 'раз в 6 дней'), (7, 'раз в неделю')], default=1, verbose_name='периодичность')),
                ('award', models.CharField(max_length=300, verbose_name='вознаграждение')),
                ('time_to_complete', models.TimeField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
